language: php

php:
  - '7.0'
  - '7.1'

services:
  - redis-server

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction

script:
  - phpdbg -qrr vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
  - php vendor/bin/php-cs-fixer --diff --dry-run -v fix
